# Generated by Django 3.2.7 on 2021-10-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
