# Generated by Django 3.2.7 on 2021-11-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_chemist',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_patient',
        ),
    ]
