# Generated by Django 3.2.7 on 2021-12-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcertificate',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approve'), ('R', 'Reject')], default='P', max_length=1),
        ),
    ]
