# Generated by Django 3.2.7 on 2021-11-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Did', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.TextField()),
                ('schedule', models.TextField()),
                ('speciality', models.CharField(max_length=20)),
                ('phonenumber', models.BigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pid',
            new_name='Pid',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
