# Generated by Django 3.2.7 on 2021-12-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211123_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Aid', models.IntegerField(primary_key=True, serialize=False)),
                ('Timings', models.TextField()),
                ('isApproved', models.BooleanField(default=False, verbose_name='IsApproved')),
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
