# Generated by Django 3.2.7 on 2021-12-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mailid',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Timings',
            field=models.CharField(max_length=20),
        ),
    ]
