# Generated by Django 3.2.7 on 2021-12-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211218_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Did',
            new_name='Doctorid',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Pid',
            new_name='Patientid',
        ),
    ]
