# Generated by Django 3.2.8 on 2021-12-21 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_medicine_patienthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='isApproved',
            field=models.BooleanField(default=True, verbose_name='IsApproved'),
        ),
        migrations.CreateModel(
            name='MedicineIssued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('prescription', models.TextField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.medicine')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient')),
            ],
        ),
    ]
