# Generated by Django 3.2.8 on 2021-12-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_medicineissued_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineissued',
            name='prescription',
            field=models.CharField(max_length=20000),
        ),
    ]
