# Generated by Django 3.2.8 on 2021-12-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_medicineissued_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineissued',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicineissued',
            name='patient',
        ),
    ]
