# Generated by Django 3.2.8 on 2021-12-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20211221_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineissued',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.medicine'),
        ),
        migrations.AddField(
            model_name='medicineissued',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient'),
        ),
    ]
