# Generated by Django 3.2.8 on 2021-12-22 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20211221_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemist',
            name='Uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chemist',
            name='phonenumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='Uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Aid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chemist',
            name='Cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Did',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phonenumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Mid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
