# Generated by Django 3.2.8 on 2021-12-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20211222_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemist',
            name='Uid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Uid',
            field=models.UUIDField(null=True),
        ),
    ]
