<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-12-22 09:28
=======
# Generated by Django 3.2.7 on 2021-12-22 09:31
>>>>>>> 5a7dd8317dadab544e025260f623d3e4d5add0df

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_uid'),
        ('users', '0023_auto_20211222_1436'),
    ]

    operations = [
    ]
