<<<<<<< HEAD
<<<<<<< HEAD

=======
>>>>>>> ef3940853de3ccddc26f9df17e986c9c91b36409
=======
# Generated by Django 3.2.7 on 2021-12-22 09:28
# Generated by Django 3.2.7 on 2021-12-22 09:31

>>>>>>> 8f480d9bd4a316e052f4f7e252ed44f1915fe762
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_uid'),
        ('users', '0023_auto_20211222_1436'),
    ]

    operations = [
    ]
