# Generated by Django 3.2.8 on 2021-12-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20211222_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Uid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phonenumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
