# Generated by Django 3.2.7 on 2021-12-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20211222_1658'),
        ('users', '0028_auto_20211222_1633'),
    ]

    operations = [
    ]
