# Generated by Django 3.2.7 on 2021-12-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_merge_0027_auto_20211222_1658_0028_auto_20211222_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcertificate',
            old_name='Did',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='medicalcertificate',
            old_name='Pid',
            new_name='patient',
        ),
    ]
