# Generated by Django 3.2.9 on 2021-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20211222_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemist',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
