# Generated by Django 3.2.8 on 2021-12-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_chemist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemist',
            name='Uid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Uid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Uid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
